### ISSUE TITLE
Command oplets to implement for release

### ISSUE THREAD

**Issue by Kenny2github** [Kenny2github/scratch-dexter#3]
[Command oplets](https://github.com/HaddingtonDynamics/Dexter/wiki/Command-oplet-instruction) to implement:
- [x] <table><td>P</td><td>"pid_move_all_joints"</td><td>PID_FINEMOVE</td><td>Chases a goal position on each joint using the PID control system which must be enabled. Requires [calibration](https://github.com/HaddingtonDynamics/Dexter/wiki/Encoder-calibration). The goal can change in the middle of the move. Movement is not coordinated so each joint may arrive at the goal at a different time. The standard trapezoidal speed ramping is not used. See "a".</td></table>
  Note: Encoder calibration is not yet a thing, and is likely to be too complicated for majority Scratch users. This block is therefore implemented but useless ._.
- [x] <table><td>g</td><td>"[get_robot_status](https://github.com/HaddingtonDynamics/Dexter/wiki/status-data)"</td><td>SEND_HEARTBEAT</td><td>Returns the current [status](https://github.com/HaddingtonDynamics/Dexter/wiki/status-data) of the robot.</td></table>
  Note: Scratch has nowhere near sophisticated enough data structures to understand the data returned by this. Probably forgo this altogether or only add it as an "update status" command; actual data parts will be returned by reporter(s):
  - [x] `([joint 1 v] [sin v])` where "joint 1" can be 1-5 and "sin" can be "position at", "position delta" etc.
  - [x] `(last [instruction number v])` where "instruction number" can be "job number", "start time", "end time", "command" etc.

**Comment by Kenny2github** [comment]
(Slapping this here so I can paste from Snipping Tool:)
![image](https://user-images.githubusercontent.com/28599280/49795842-019f8580-fd76-11e8-8fe3-737214784d3e.png)

**Comment by JamesNewton** [comment]
The pid move all joints is just like move all joints, but it uses the PID engine to "chase" the goal point. It sort of applies a force in the correct direction. It's what we use in the "sender / follower" demos when we are operating one arm from the other. That's why the follower arm moves really smoothly and sort of lags behind the others. 

On the boundaries, I'm not sure it's worth implementing as a first release item. I don't see a way to do it except as a very long list of numbers.

On the status, it might be worth just keeping the returned value from each command in an array inside the extension, then just add access to different status items over time. E.g. Joint 6 position is really handy so you can use the "wrist" dynamixel servo as an input device to select options. 

One thing that could be very valuable is access to the torque on each joint, which is derived from those status values as documented here:
https://github.com/HaddingtonDynamics/Dexter/issues/13#issuecomment-420105963
This can be used to trigger events, such as any_joint_torque_exceeds which can be used to just stop the robot, or (more useful) find an object or surface by sense of touch.

**Comment by Kenny2github** [comment]
I just realized that a menu for which boundary to set would be far more concise... i.e. "set boundary [j1 upper v] to ()" where "j1 upper" is one of the boundaries. I'll update the OP.

**Comment by JamesNewton** [comment]
Keep in mind that when you send the command to Dexter, you must specify all the boundaries. So if you want to allow the user to set only one, you must first load an array with the default values, so that they can be sent along with the one the user changes. I also don't think changing the boundaries is useful or anything but confusing to the average scratch user. I'd recommend just leaving that one off.

**Comment by Kenny2github** [comment]
I see your point... updated OP once more

**Comment by Kenny2github** [comment]
Will be working on this next Thursday after school

**Comment by JamesNewton** [comment]
I've updated the description of the 'a' and 'p' oplets to clarify and correct my understanding. On the PID move, there isn't a "force" it's a goal position and the goal can change during the move, but the joints don't coordinate. The 'a' move does coordinated movement, but you can't change the goal until it reaches it. Sorry about the confusion, I'm still learning:
https://github.com/HaddingtonDynamics/Dexter/wiki/Command-oplet-instruction

**Comment by Kenny2github** [comment]
New blocks for completed oplets:
![image](https://user-images.githubusercontent.com/28599280/50278984-787a0400-0483-11e9-9f7f-d8c270f90b20.png)
Various status reporters:
![image](https://user-images.githubusercontent.com/28599280/50279070-b24b0a80-0483-11e9-8c22-f0a857f0fe38.png)
Various "last" reporters:
![image](https://user-images.githubusercontent.com/28599280/50279098-c7279e00-0483-11e9-9d1d-e672b6af628e.png)
Various J6&7-specific reporters:
![image](https://user-images.githubusercontent.com/28599280/50279130-dc9cc800-0483-11e9-8e22-353d2bf264fb.png)
"get robot status" updates the status reporters in case no recent instructions have been sent. "reload" is used if the socket connection is closed or needs to be reloaded for some reason, probably will be removed at some point.

**Comment by JamesNewton** [comment]
So first, this is really great and this enables a lot of really cool programs to be written for the robot!

Sorry I wasn't clear in my documentation of the PID move, but anything using the PID system requires that the robot be in a closed loop mode like Keep mode and those require calibration so the encoder system is working. When Dexter boots, it's open loop. The encoders do NOT work. But after Calibration, if the individual joint encoder "eyes" are "good" (they make a circle and the center is set) then the robot will know where it's joints are, and can use that feedback to update it's position. Keep mode also turns on the PID system. See the "Calibrate Dexter..." dialog on the "Jobs" menu in DDE for the procedure for this. Also in DDE on the "Jobs" menu, under "Run instruction" / "Show dialog..." you can switch between modes. Make sure you have the latest LTR version of DDE and updated DexRun.C Firmware and xillydemo.bit Gateware installed on the robot. 

And just now writing that it dawns on me that I should have mentioned the SetParameter RunFile command. You might be able to write a calibration script in scratch, but it would be far easier to just RunFile the [Cal.make_ins](https://github.com/HaddingtonDynamics/Dexter/blob/master/Firmware/Cal.make_ins) file from the robot which would put it into keep mode. (again, assuming the joint eyes are good and the centers are set via DDE). RunFile also allows easy playback of complex sequences. The RunFile command was implemented in this release, which has detailed documentation about it:
https://github.com/HaddingtonDynamics/Dexter/commit/e3cccb88cf9b1671c5b2f13c77d1ee00a967a528

And if you didn't know about the Calibration thing, you might not realize that most of the joint reporters won't work outside of a calibrated mode like Keep or Follow. E.g. there are no measured angles available unless the encoders are on. Measured angles also requires updated Gateware. We should talk more about those modes. Anyway, that gives you something for the next release.

Most of the blocks you have now WILL work nicely for operation in Open loop mode (which is what the robot boots into) and I'm looking forward to demoing them at a Scratch day here.

**Comment by Kenny2github** [comment]
I think these are enough for first release.

**Comment by JamesNewton** [comment]
Sample program
![ScratchDexterWiggle2](https://user-images.githubusercontent.com/419392/57275528-b8690e80-7053-11e9-8ebf-120c13898d7f.png)
